config/routes.rb
Arachne::Application.routes.draw do 
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root  'users#index'
  
  resources :sessions
  resources :users, path: "" do 
    resources :thoughts
  end
end

app/models/thought.rb
class Thought < ActiveRecord::Base
  belongs_to :user

  validates :content, presence: true
            
  validates_uniqueness_of :title, :allow_blank => true, :case_sensitive => false
  
  def self.text_search(query)
  	if query.present?
      where("title like :q or content like :q", q: "%#{query}%")
  	else
  		scoped
  	end
  end

  def self.tags_search(query)
    if query.present?
      where("title like :q or tags like :q", q: "%#{query}%")
    else
      scoped
    end
  end

  def self.all_search(query)
    if query.present?
      where("title like :q or content like :q or tags like :q", q: "%#{query}%")
    else
      scoped
    end
  end


# not in use
  def self.title_search(query)  
    if query.present?
      where("title like :q", q: "%#{query}%")
    else
      scoped
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # vanity url by username
  extend FriendlyId
  friendly_id :username

  has_many :thoughts, dependent: :destroy
  has_secure_password


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


private

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	helper_method :current_user

	def authorize

        if params[:user_id]
        	redirect_to root_url, alert: "Not authorized" if current_user.id.to_s != params[:user_id].to_s
        elsif params[:id]
        	redirect_to root_url, alert: "Not authorized" if current_user.id.to_s != params[:id].to_s
        end

        
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	@user = User.find_by_username(params[:username])
  	if @user && @user.authenticate(params[:password])
  		session[:user_id] = @user.id
  		redirect_to @user
      # flash[:success] = "Logged in!"
  	else	

  		redirect_to root_url
      flash[:alert] = "Username or password is invalid"

  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_url
    # flash[:success] = "Logged out!"
  end
end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
	# before_filter :authorize
	before_action :set_user

	def index
		@thoughts = @user.thoughts
		@thoughts_search = Thought.text_search(params[:query])
		@thought = @user.thoughts.first
	end

	def new
		@thought = @user.thoughts.new
		# redirect_to edit_user_path(@user)
		respond_to do |format|
	    	format.js
	    end
	end
	
	def create
	  @thoughts = @user.thoughts
	  @thought = @user.thoughts.new(thought_params)
	  # @thoughts_search = @user.thoughts.text_search(params[:query])
	  if @thought.save
	  	  respond_to do |format|
	      format.js
	    end
	    # flash[:success] = "Thanks for your thought!"
	  else
	    render :new
	  end
	end

	def show
		@thoughts = @user.thoughts
		@thought = @user.thoughts.find(params[:id])
		@thoughts_search = Thought.text_search(params[:query])
		respond_to do |format|
	    	format.js
	    end
	end

	def edit
		@thought = @user.thoughts.find(params[:id])
		@thoughts = @user.thoughts
		# render :edit
		# redirect_to edit_user_path(@user)
		respond_to do |format|
	    	format.js
	    end
	end

	def update
		@thought = @user.thoughts.find(params[:id])
		@thoughts = @user.thoughts
	    if @thought.update(thought_params)
		# redirect_to edit_user_path(@user)
	    respond_to do |format|
	    	format.js
	    end 
	      # flash[:success] = "Thought successfully updated!"
	    else
	      render :edit
	    end
    end

	def destroy
		@thought = @user.thoughts.find(params[:id])
	    @thought.destroy
	    @thoughts = @user.thoughts
	    @thought = @user.thoughts.new
	    respond_to do |format|
	    	format.js
	    end
	end

private

def thought_params
  params.require(:thought).permit(:content, :title, :tags)
end

def set_user
  @user = User.find_by_username(params[:user_id])
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	# before_filter :authorize, only: [:show, :edit]


	def index
		@user = User.new
		if current_user
			redirect_to current_user
		end
	end

	def show
		@user = User.find_by_username(params[:id])
		@thoughts = @user.thoughts
		@thoughts_search = @user.thoughts.tags_search(params[:query])
		@thoughts_title_search = @user.thoughts.title_search(params[:query])
		@thought = @user.thoughts.new
		respond_to do |format|
	    	 format.html {if params[:query]	
			@thought_edit = @thoughts_search.first
		elsif params[:id_edit]
			@thought_edit = @user.thoughts.find(params[:id_edit]) 
	    end}
	    	format.js
	    end
	    if params[:query]	
			@thought_edit = @thoughts_search.first
		elsif params[:id_edit]
			@thought_edit = @user.thoughts.find(params[:id_edit]) 
	    end
	end

	def new
		@user = User.new
	end

	def create
		
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			UserMailer.signup_confirmation(@user).deliver
			@thought = @user.thoughts.create(content: "This is a non-titled thought, All tags of a non-titled thought are represented in a non-hierarchical web and of a particular color.", tags: "thought,non-hierarchical,web,color")
			@thought = @user.thoughts.create(content: "This is some test text. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", title:"Title Text", tags: "Lorem,ipsum,dolor,sit,amet")
			@thought = @user.thoughts.create(content: "This is a non-titled thought, All tags of a non-titled thought are represented in a  non-hierarchical web and in a particular color.", tags: "titled,diamond,line,node,graph",title:"Read Me")
			@thought = @user.thoughts.create(content: "This is a non-titled thought, All tags of a non-titled thought are represented in a  non-hierarchical web and in a particular color.", tags: "14,243,35,45,55,655,57,58")
			@thought = @user.thoughts.create(content: "This is some test text. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", tags: "sit,amet,consectetur,adipisicing,elit,sed")
			
			redirect_to @user, notice: "Thank you for signing up! A confirmation email has been sent to your address."
		else
			render "new"
		end
	end

	def edit
		@user = User.find_by_username(params[:id])
		@thoughts = @user.thoughts
		@thoughts_search = @user.thoughts.tags_search(params[:query])
		@thought = @user.thoughts.new
		
	    if params[:query]	
	    	@thoughts = @user.thoughts.all_search(params[:query])
			@thought_edit = @thoughts_search.first
			# @thoughts = @thoughts_search.first
		elsif params[:id_edit]
			@thought_edit = @user.thoughts.find(params[:id_edit]) 
	    end
		
	end

	private

    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
# require 'redcarpet'

module ApplicationHelper

	def mark_it_down(text)
		require 'redcarpet'
		markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, hard_wrap: true)
		markdown.render(text).html_safe
	end

	# def syntax_highlighter(html)
	#   doc = Nokogiri::HTML(html)
	#   doc.search("//pre[@lang]").each do |pre|
	#     pre.replace Albino.colorize(pre.text.rstrip, pre[:lang])
	#   end
	#   doc.to_s
	# end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/thoughts_helper.rb
module ThoughtsHelper

	def web_array_maker(thoughts)
		thought_web_array=[] 
		thoughts.each do |thought|
		title_string=  thought.title.to_s.titleize
	 	 if title_string.length == 1
			str=  thought.tags.to_s   
		    tags = str.split(",")
			thought_web_array= thought_web_array+[tags] 	
	 	 else
	 	 	str=  thought.tags.to_s   
		    tags = str.split(",")
		    title_array = tags.unshift(title_string)
			thought_web_array= thought_web_array+[title_array] 
	 	 end
		end 
		return thought_web_array
	end

	

end

app/helpers/users_helper.rb
module UsersHelper



end

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
          <%if current_page?(signup_path)%>
          <span><%= link_to "arachne.io", root_path, class: "brand", id: "logo" %> <%= image_tag"spider.png" %></span>
          
          <% elsif params[:id] && current_page?(edit_user_path)%>
          <span><%= link_to "arachne.io", user_path(@user), class: "brand", id: "logo" %> <%= image_tag"spider.png" %></span>

          <% else %>
          <span><p class="brand" id="logo">arachne.io</p> <%= image_tag"spider.png" %></span>
          
          <% end %>
        </div>
       
        <div class="collapse navbar-collapse">

          <ul class="nav navbar-nav pull-right">

            <p class="navbar-text" style="color: #b52a2a;">
            <% if flash[:alert] %>
              <%= flash[:alert] %>
            <% end %>
            </p>

            <p class="navbar-text" style="color:green;">
            <% if flash[:success] %>
              <%= flash[:success] %>
            <% end %>
            </p>
           
            <p class="navbar-text" id="saved" class="navbar-text" style="display:none;">Saving...</p>
            <p class="navbar-text" id="deleted" class="navbar-text" style="display:none;">Deleting...</p>

            <% if current_user %>

           <li><p class="navbar-text" id="logged-in-text">Logged in as <%=current_user.username%> !</p></li>
           <li><%= link_to "Log Out", logout_path, 'data-no-turbolink' => true %></li>
           </ul>
           <% else %>

            </ul>

              <%= form_tag sessions_path, class: "navbar-form navbar-right", method: :post do %>
              <div class="form-group">

              <%= text_field_tag :username, nil, :class=>"form-control", :placeholder =>"Username" %>
              </div>
              <div class="form-group">
                <%= password_field_tag :password, nil, :class=>"form-control", :placeholder => "Password" %>
                </div>
                <div class="form-group">
                <%= submit_tag "Log In", class: "btn btn-success", style: "color:black;" %>
                </div>
              <!-- </form> -->
          <% end %>
          <% end %>
          
          <!-- </ul> -->
        </div><!--/.nav-collapse -->
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arachne Writer.</title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    
  </head>
  <body>
   
    <%= render 'layouts/header' %>
    <!-- <div class="container"> -->
     
      <%= yield %>
      
         <!-- <%= debug(params) if Rails.env.development? %>    -->
    <!-- </div> -->

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.thoughts.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/thoughts/_list.html.erb
<% @thoughts.each_with_index do |thought, index|%>
<% if thought.content %>

<a class="btn btn-default" id="downChev" data-id="<%= index %>"><span class="glyphicon glyphicon-chevron-down"></span></a>

<% if @thought.id == thought.id %>
<a data-remote="true" href="/<%= @user.username %>/thoughts/<%= thought.id %>/edit" class="list-group-item active" data-thoughtid="<%= @thought.id %>">
<% else %>
<a data-remote="true" href="/<%= @user.username %>/thoughts/<%= thought.id %>/edit" class="list-group-item" data-thoughtid="<%= @thought.id %>">
<% end %>

<h4 class="list-group-item-heading">

    <% if thought.title %>
        <strong><%=  thought.title.titleize %></strong>
    <% end %>
</h4>

<p class="list-group-item-text">

<span class="hashSubTitle">
 <% if thought.tags  %>
  <% thought.tags.split(',').each do |tag| %>
    <p class="tagListClass">
    <%= tag %>
    </p>

 <% end %>

 <% end %>
 </span>

<% if thought.tags  %>
    <% if thought.tags.split(',').length > 0 %>
     <br />  
    <% end %>
<% end %>

   <%=  truncate(thought.content, :length => 150) %>
 
</p>

</a>
<p class="toggledContent" style="display:none;" id="PID<%= index %>">
    <%= thought.content %>
</p>

<% end %> 
<% end %> 

app/views/thoughts/_markdown.html.erb
<div id="newForm" style="padding-bottom: 11px;">
	<%= link_to "Markdown", edit_user_thought_path(@user, @thought), class: "btn btn-primary black-btn", remote: true, method: :get %>
	<%= link_to "Preview", user_thought_path(@user, @thought), class: "btn btn-primary black-btn active", remote: true, method: :get %>
	
	<div class="markdown_preview">
		<%= @thought.title  %>
		<br />
		<%= mark_it_down(@thought.content)  %>
	</div>
</div>

app/views/thoughts/_single.html.erb
       
       <%= @thought.content %>
      
   
      

app/views/thoughts/_thought.html.erb
<%= form_for [@user, @thought], :html => { :id => "newForm" },remote: true do |f| %>
<!-- dynamic active thought variable for delete jquery-->
<%= javascript_tag do %>
  window.thoughtid = "<%= @thought.id %>";
  window.userName = "<%= @user.username %>";
  window.userid = "<%= @user.id %>";
<% end %>


  <fieldset style="height:100%;">

<!-- <a data-remote="true" href="/<%= @user.username %>/thoughts/<%= @thought.id %>" class="btn btn-default black-btn" id="markdown" >Markdown</a> -->

<%= link_to "Markdown", edit_user_thought_path(@user, @thought), class: "btn btn-primary black-btn active", remote: true, method: :get %>
<%= link_to "Preview", user_thought_path(@user, @thought), class: "btn btn-primary black-btn", remote: true, method: :get %>

<div class="markdown_markdown">
	      <!-- <%= f.submit%> -->
	      <%= f.text_field :title, class: "form-control", placeholder: "Title"%>
          <%= f.text_area :content, autofocus: true, class: "form-control writingClass" %>    
	      <%= f.text_field :tags, class: "form-control tagClass", placeholder: "Enter tags...", 'data-role' => "tagsinput"%>
  </fieldset>
<% end %>

</div>

<style type="text/css">
	
	.markdown_markdown{
	
		height: 100%;
		/*padding: 15px;*/
		margin-top: 2px;
		/*padding-bottom: 42px;*/
		
	}
</style>

app/views/thoughts/_title.html.erb
 <% mod = @thought.content.scan(/#\w+/) %>
                 
                 <% if mod[0] %>
                 <% title = mod[0].titleize %>
                 <% title[0] = "" %>
                 <% else %>
                 <% title = mod[0]%>
                 <% end %>

                 <strong><%= title %></strong>

app/views/thoughts/edit.html.erb
<%= form_for([@user, @thought]) do |f| %>
<%= render "shared/error_messages", object: @thought %>
  <fieldset>
    <!-- <ol> -->
      <!-- <li class="required"> -->
        <!-- <%= f.label :content %>          -->
        <%= f.text_area :content, autofocus: true, rows: 10 %>
      <!-- </li> -->
  
    <!-- </ol> -->
    <p>
      <%= f.submit 'Save', class: "btn btn-primary" %> 
      <%= link_to "New", @user, class: 'button' %> |
      <%= link_to "Delete", user_thought_path(@user, @thought), method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  </fieldset>
<% end %>

<ul>
  <% @thoughts.each do |thought| %>
    <li>
      
      
      
      
      <%= link_to thought.content, edit_user_thought_path(@user, thought) %>
      
    </li>
  <% end %>
</ul>




  <div >
  <h1>#hashtag nodes</h1>
  
  <div class="span12 sigma-parent" id="sigma-example-parent">
    <div class="sigma-expand" id="sigma-example"></div>
  </div>
</div>



<% xx=[] %>
<% @thoughts.each do |thought| %>
 
 <% thought.content.to_s   %>
 
 <% str=  thought.content.to_s   %>
 

 <% tags = str.scan(/#\w+/).uniq %>
 
   


 <%xx= xx.concat tags %>
 
<% end %>



<%= javascript_tag do %>
  window.userName = "<%=j @user.username %>";
  window.nodeCount = "<%= @thoughts.size %>";
  window.hashArray = <%=raw xx.as_json %>;


<% end %>

app/views/thoughts/index.html.erb
<!-- <h1> show page </h1> -->
<%= form_tag user_thoughts_path(@user), method: :get do %>
<p>
  <%= text_field_tag :query, params[:query] %>
  <%= submit_tag "Search", name: nil %>
</p>
<% end %>



<%= form_for([@user, @thought]) do |f| %>
<%= render "shared/error_messages", object: @thought %>
  <fieldset>
    
     
        <!-- <%= f.label :content %>          -->
        <%= f.text_area :content, autofocus: true, rows: 10  %>
      
  
    
    <p>
      <%= f.submit 'Save', class: "btn btn-primary" %> 
      
    </p>
  </fieldset>
<% end %>


<ul>
  <% @thoughts_search.each do |thought| %>
    <li>
      
      <%= link_to thought.content, edit_user_thought_path(@user, thought) %>
      
    </li>
  <% end %>
</ul>



    <div >
  <h1>#hashtag nodes</h1>
  
  <div class="span12 sigma-parent" id="sigma-example-parent">
    <div class="sigma-expand" id="sigma-example"></div>
  </div>
</div>



<% xx=[] %>
<% @thoughts.each do |thought| %>
 
 <% thought.content.to_s   %>
 
 <% str=  thought.content.to_s   %>
 

 <% tags = str.scan(/#\w+/).uniq %>
 
   


 <%xx= xx.concat tags %>
 
<% end %>



<%= javascript_tag do %>
  window.userName = "<%=j @user.username %>";
  window.nodeCount = "<%= @thoughts.size %>";
  window.hashArray = <%=raw xx.as_json %>;


<% end %>

app/views/thoughts/new.html.erb
<%= form_for [@user, @thought], :html => { :id => "newForm" },remote: true do |f| %>
<!-- dynamic active thought variable for delete jquery-->
<%= javascript_tag do %>
  window.thoughtid = "<%= @thought.id %>";
<% end %>
<%= render "shared/error_messages", object: @thought %>
  <fieldset style="height:100%;">

        <%= f.text_area :content, autofocus: true, class: "form-control writingClass"  %>
      
  </fieldset>
<% end %>

app/views/thoughts/show.js.erb
$('#newForm').remove();
$('#bucket').append('<%= j render :partial => 'thoughts/markdown' %>');

$('.list-group').remove();
$('.sideScrollBar').append('<div class="list-group"><%= j render :partial => 'thoughts/list' %></div>');


//node mode

$('.modal-body').empty();
$('#myModalLabel').empty();

$('.modal-body').append('<%= j render :partial => 'thoughts/single' %>');
$('#myModalLabel').append('<%= j render :partial => 'thoughts/title' %>');

app/views/thoughts/update.js.erb
$('.list-group').remove();
$('.sideScrollBar').append('<div class="list-group"><%= j render :partial => 'thoughts/list' %></div>');

app/views/users/_modal.html.erb
<%= javascript_tag do %>
  window.thoughtid = "<%= @thoughts_search.first.id %>";
<% end %>


<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">
       

         
          
                 
                

      

                

                 <strong><%= @thoughts_search.first.title%></strong>



             

               

        </h4>
      </div>
      <div class="modal-body">

      
       
       <%= mark_it_down(@thoughts_search.first.content)  %>
      
      </div>
      <div class="modal-footer">
      <% if @thoughts_search.count > 1  %>

      <h4 id="hashSearched">All nodes connecting to  <strong><%= params[:query]%></strong></h4>
      <div class="list-group">
      <!-- the first thought is already displayed in the modal content, no the if statment ignores it  -->
      <% @thoughts_search.each do |thought|%>
      
      
      
   
    
      <a data-remote="true" href="/<%= @user.id %>/thoughts/<%= thought.id %>/" class="list-group-item" data-thoughtid="<%= thought.id %>">
                 <h4 class="list-group-item-heading">
                
                <% mod = thought.content.scan(/#\w+/).uniq %>
                 
                 <% if mod[0] %>
                 <% title = mod[0].titleize %>
                 <% title[0] = "" %>
                 <% else %>
                 <% title = mod[0]%>
                 <% end %>
                 
                 <strong><%= title %></strong>
                 <span class="hashSubTitle">
                 <%=  thought.content.scan(/#\w+/).uniq %>
                 </span>
                 </h4>
                
              </a>
       
     
  <% end %> 
  </div>
  <% else %> 
        <!-- <button type="button" class="btn btn-danger" id="deleteM">Delete</button> -->
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  <% end %> 

      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>

app/views/users/edit.html.erb
<style type="text/css">
html{
  overflow:hidden;
}
body{
  background-color: gray;
}
</style>

<div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation" style="height:100%; padding-bottom:10px;">

<%= form_tag edit_user_path(@user),:id => 'submit_id', method: :get do %>
  <%= text_field_tag :query, params[:query], :placeholder => "search", class: "form-control" %>
  <%= submit_tag "Search", name: nil, class: "btn btn-default", style: "display:none;" %>
<% end %>

  <div class="sideScrollBar">
    <div class="list-group"> 
       
        <%= render "thoughts/list"%>
   
    </div>
  </div>
  
</div>

<div id="bucket" class="col-xs-12 col-sm-9" >
    
    
 <div class="left_buttons ">
 
 </div>


<div class="right_buttons">
        <!-- <%= link_to "New", new_user_thought_path(@user), class: "btn btn-primary black-btn", remote: true %> -->

        <button type="button" class="btn btn-default black-btn" id="newThought">New</button>
        <button type="button" class="btn btn-default black-btn" id="save">Save (Ctrl+S)</button>
        <button type="button" class="btn btn-default black-btn" id="delete">Delete</button>
        <%= link_to "Display Mode", @user, class: "btn btn-success black-btn", 'data-no-turbolink' => true %>
</div>

       <%= render "thoughts/thought"%>
 
   <div style="display:none;" class="sigma-parent" id="sigma-example-parent" >
      <div class="sigma-expand" id="sigma-example" ></div>
  </div>

</div>

app/views/users/index.html.erb
<%= javascript_include_tag 'sigma/title_sigma.js' %> 

<style type="text/css">
body {
  background-color: black;
  /*padding-top: -100px;*/
  /*height: 100%;*/
}
  .sigma-parent {
    position: relative;
    top: -50px;
    border-radius: 4px;
    -moz-border-radius: 4px;
    -webkit-border-radius: 4px;
    background: black;
    height: 70%;
  }

</style>

<h1 style="color:white;">Welcome to arachne.io </h1><h2 style="color:#e6e6e6;">
  A writing environment by <a href="http://rolandsharp.com/" target="_blank">rolandsharp.com</a>.
</h2>

<div class="sigma-parent" id="sigma-expand">
    <div class="sigma-expand" id="sigma-example"></div>
</div>
    
<div class="sign-up-div"><%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-success", id: "sign-up-button" %></div>

app/views/users/new.html.erb
<%= javascript_include_tag 'sigma/sign_up_sigma.js' %> 

<style type="text/css">
body {
  background-color: black;
  /*padding-top: -100px;*/
  height: 100%;
}
  .sigma-parent {
    position: relative;
    z-index: -1;
    top: -250px;
    border-radius: 4px;
    -moz-border-radius: 4px;
    -webkit-border-radius: 4px;
    background: black;
    height: 90%;
  }

  #sign-up-form{
  	position: absolute;
  	
  	top: 50px;
  	/*padding-left: 200px;*/
  }

</style>



<div class="container" style="color:white;">
<h1 style="position:relative; top:10px; color:#47a447;">Sign up</h1>

<div class="row">
<div class="col-md-4"></div>
  <div class="col-md-4">
 
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

	     
	      <%= f.text_field :username, :class=>"form-control", placeholder: "Username", style: "position:relative; top: 20px;" %>

	      <%= f.text_field :email, :class=>"form-control", placeholder: "Email", style: "position:relative; top: 40px;" %>

	     
	      <%= f.password_field :password, :class=>"form-control", placeholder: "Password", style: "position:relative; top: 60px;" %>

	  
	      <%= f.password_field :password_confirmation, :class=>"form-control", placeholder: "Password Confirmation", style: "position:relative; top: 80px;" %>

	      <%= f.submit "Create my account", class: "btn btn-large btn-success", style: "color:black; position:relative; top: 100px;" %>
    <% end %>
 
  </div>
  <div class="col-md-4"></div>
</div>
</div>

<div class="sigma-parent" id="sigma-expand">
    <div class="sigma-expand" id="sigma-example"></div>
</div>

app/views/users/show.js.erb
$('#myModal').remove();
$('#modalDiv').append('<%= j render :partial => 'users/modal' %>');
$('#myModal').modal('show');

// $('#deleteM').on('click', function() { 
//     confirm("Are you sure?");
//     console.log(thoughtid);
//     $.post("/users/"+userid+"/thoughts/"+thoughtid+"/", { _method: 'delete' }, null, "script");

//     $('#myModal').modal('hide');


    
 // });